package com.jdw.mapper;

import com.jdw.entity.Ticket;
import com.jdw.entity.TicketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int countByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int deleteByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int insertSelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    List<Ticket> selectByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    Ticket selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ticket record, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int updateByExample(@Param("record") Ticket record, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int updateByPrimaryKeySelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    int updateByPrimaryKey(Ticket record);
}