package com.jdw.entity;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.id
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.create_time
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.user_id
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.id
     *
     * @return the value of t_ticket.id
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.id
     *
     * @param id the value for t_ticket.id
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.create_time
     *
     * @return the value of t_ticket.create_time
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.create_time
     *
     * @param createTime the value for t_ticket.create_time
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.user_id
     *
     * @return the value of t_ticket.user_id
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.user_id
     *
     * @param userId the value for t_ticket.user_id
     *
     * @mbggenerated Mon Nov 02 16:08:51 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}