package com.hd.domain.vo;

import java.io.Serializable;

public class UserInfoVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.info
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.info
     *
     * @return the value of user_info.info
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.info
     *
     * @param info the value for user_info.info
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Wed Oct 28 18:17:50 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}